# Generated by Django 3.2 on 2021-04-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myposts', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='post snippet', max_length=255),
        ),
    ]
